In [1]:
!pip install numpy

In [6]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3])

In [8]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
np.random.rand(3, 2)

array([[0.56363342, 0.83379388],
       [0.62952248, 0.52501151],
       [0.76830221, 0.52283048]])

In [16]:
np.random.randn(3, 2)

array([[ 1.59087898, -1.22907339],
       [-0.32828388,  0.14603511],
       [ 0.49279856, -0.46144454]])

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [18]:
print(arr.shape)

(2, 3)


In [19]:
print(arr.ndim)

2


In [20]:
print(arr.size)

6


In [21]:
print(arr.dtype)

int64


In [22]:
a = np.array([1, 2, 3])


In [23]:
b = np.array([4,5,6])

In [24]:
a+b

array([5, 7, 9])

In [25]:
a*b

array([ 4, 10, 18])

In [26]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [28]:
A = np.array([[1,2],[3,4]])

In [29]:
B= np.array([[5,6],[7,8]])

In [30]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [31]:
A@B

array([[19, 22],
       [43, 50]])

In [32]:
arr = np.array([1, 2, 3, 4])

In [33]:
arr.sum()

np.int64(10)

In [34]:
arr.mean()

np.float64(2.5)

In [35]:
arr.max()

np.int64(4)

In [36]:
arr.min()

np.int64(1)

In [37]:
arr.min()

np.int64(1)

In [38]:
arr.std()

np.float64(1.118033988749895)

In [39]:
arr = np.array([1,2,3,4,5])

In [40]:
arr[0]

np.int64(1)

In [41]:
arr[1:4]

array([2, 3, 4])

In [42]:
arr[::2]

array([1, 3, 5])

In [43]:
arr = np.array([1,2,3,4,5])

In [44]:
mask = arr>3

In [43]:
arr[mask]

array([4, 5])

In [45]:
arr = np.arange(6)

In [46]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
a= np.array([1,2])



In [48]:
a= np.array([1,2])



In [49]:
b = np.array([3, 4])


In [50]:
np.concatenate((a, b))

array([1, 2, 3, 4])

In [51]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [53]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [52]:
a = np.array([1,2,3])

In [56]:
a+5

array([6, 7, 8])

In [53]:
np.save('array.npy',arr)

In [60]:
loaded_arr = np.load('array.npy')